name: Linting and type checking and testing

on:
  push:
  schedule:
    - cron: "0 2 */2 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      matrix:
        node-version: [22.x, 24.x]

    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.OS }}-build-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ matrix.node-version }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install
        run: npm install

      - name: Lint
        run: npm run check

      - name: Build
        run: npm run build

      - name: Integration test
        run: npm run integrationTest
